# Inicialização e organização dos rótulos

In [1]:
import pandas as pd
import glob
import os

In [2]:
df = pd.read_csv('/content/drive/MyDrive/lagenda/lagenda_annotation.csv')

idades_por_imagem = (
    df.groupby('img_name')['age']
      .apply(lambda x: list(x) if (x != -1).all() else None)
      .dropna()
      .reset_index()
)
# tem uma imagem faltando nos arquivos
idades_por_imagem = idades_por_imagem[idades_por_imagem['img_name'] != 'lag_benchmark/b5c8ef090f134ad5.jpg.jpg'].reset_index()

print(f"{len(idades_por_imagem)} imagens têm todas as idades conhecidas.")
display(idades_por_imagem)

20182 imagens têm todas as idades conhecidas.

       index                            img_name     age
0          0  lag_benchmark/0000339d0372e7e6.jpg    [27]
1          1  lag_benchmark/0004350a376865f5.jpg  [5, 6]
2          2  lag_benchmark/00059fa95ee95e65.jpg    [79]
3          3  lag_benchmark/0007473cdbe8c18d.jpg     [6]
4          4  lag_benchmark/000851174d48d3d9.jpg     [4]
...      ...                                 ...     ...
20177  20178  lag_benchmark/fff74322fa07c7c1.jpg    [41]
20178  20179  lag_benchmark/fff934bd1ff95af5.jpg    [76]
20179  20180  lag_benchmark/fffb40d02f510b35.jpg    [18]
20180  20181  lag_benchmark/ffff1ad4bf685255.jpg    [22]
20181  20182  lag_benchmark/ffff369453fcbdde.jpg    [54]

[20182 rows x 3 columns]

In [ ]:
real_prompt1 = []
for idade in idades_por_imagem['age']:
  jovem = min(idade)
  if jovem < 14: #### menor que 14 :D
     valor = "1"
  else:
    valor = "0"
  real_prompt1 += [valor]
print(len(real_prompt1))

20182

In [ ]:
real_prompt2 = []
for idade in idades_por_imagem['age']:
  jovem = min(idade)
  if jovem < 18:
     valor = "1"
  else:
    valor = "0"
  real_prompt2 += [valor]

In [ ]:
real_prompt3 = []
for idade in idades_por_imagem['age']:
  jovem = min(idade)
  if jovem <= 13: #mudei
     valor = "criança"
  elif 13 < jovem <= 17: #mudei
    valor = "adolescente"
  elif 18 <= jovem <= 59:
    valor = "adulto"
  else:
    valor = "idoso"
  real_prompt3 += [valor]

In [ ]:
real_prompt4 = []
for idade in idades_por_imagem['age']:
  jovem = min(idade)
  real_prompt4 += [jovem]

real = [real_prompt1, real_prompt2, real_prompt3, real_prompt4]

# Construção da Tabela de resultados sem Oclusão

In [ ]:
resultadosIntern = pd.DataFrame()

In [ ]:
# pasta onde estão os csvs
PASTA_CSV = "/content/drive/MyDrive/lagenda/resultados_InternVL/grupo1"

# pega todos os arquivos csv
arquivos = sorted(
    glob.glob(os.path.join(PASTA_CSV, "*.csv")),
    key=lambda x: int(x.split("_p")[-1].split(".")[0])
)
print(arquivos)

# dataframe final
resultadosIntern['img_name'] = idades_por_imagem['img_name']

# percorre cada csv
for i, arquivo in enumerate(arquivos, start=1):

    # lê csv
    df_result = pd.read_csv(arquivo)

    nome_prev = f"previsao_prompt{i}"
    nome_real = f"real_prompt{i}"

    resultadosIntern[nome_prev] = df_result["resposta_modelo"]
    resultadosIntern[nome_real] = real[i-1]

resultadosIntern

['/content/drive/MyDrive/lagenda/resultados_InternVL/grupo1/resultados_internvl3_p1.csv', '/content/drive/MyDrive/lagenda/resultados_InternVL/grupo1/resultados_internvl3_p2.csv', '/content/drive/MyDrive/lagenda/resultados_InternVL/grupo1/resultados_internvl3_p3.csv', '/content/drive/MyDrive/lagenda/resultados_InternVL/grupo1/resultados_internvl3_p4.csv']

,img_name,previsao_prompt1,real_prompt1,previsao_prompt2,real_prompt2,previsao_prompt3,real_prompt3,previsao_prompt4,real_prompt4
0,lag_benchmark/0000339d0372e7e6.jpg,0.0,0,0.0,0,Adulto,adulto,25,27
1,lag_benchmark/0004350a376865f5.jpg,1.0,1,1.0,1,Criança (0,criança,4,5
2,lag_benchmark/00059fa95ee95e65.jpg,0.0,0,0.0,0,Idoso,idoso,60,79
3,lag_benchmark/0007473cdbe8c18d.jpg,1.0,1,1.0,1,Criança (0,criança,4,6
4,lag_benchmark/000851174d48d3d9.jpg,1.0,1,1.0,1,Criança (0,criança,3,4
...,...,...,...,...,...,...,...,...,...
20177,lag_benchmark/fff74322fa07c7c1.jpg,0.0,0,0.0,0,Adulto,adulto,40,41
20178,lag_benchmark/fff934bd1ff95af5.jpg,0.0,0,0.0,0,Idoso,idoso,80,76
20179,lag_benchmark/fffb40d02f510b35.jpg,1.0,0,1.0,0,Adolescente,adulto,15,18
20180,lag_benchmark/ffff1ad4bf685255.jpg,0.0,0,0.0,0,Adulto,adulto,25,22
20181,lag_benchmark/ffff369453fcbdde.jpg,0.0,0,0.0,0,Adulto,adulto,50,54

In [ ]:
resultadosIntern['previsao_prompt1'] = (resultadosIntern['previsao_prompt1'].astype(float).astype(int).astype(str))
resultadosIntern['previsao_prompt2'] = (resultadosIntern['previsao_prompt2'].astype(float).astype(int).astype(str))
resultadosIntern['real_prompt2'] = resultadosIntern['real_prompt2'].astype(str)

In [ ]:
resultadosIntern

,img_name,previsao_prompt1,real_prompt1,previsao_prompt2,real_prompt2,previsao_prompt3,real_prompt3,previsao_prompt4,real_prompt4
0,lag_benchmark/0000339d0372e7e6.jpg,0,0,0,0,Adulto,adulto,25,27
1,lag_benchmark/0004350a376865f5.jpg,1,1,1,1,Criança (0,criança,4,5
2,lag_benchmark/00059fa95ee95e65.jpg,0,0,0,0,Idoso,idoso,60,79
3,lag_benchmark/0007473cdbe8c18d.jpg,1,1,1,1,Criança (0,criança,4,6
4,lag_benchmark/000851174d48d3d9.jpg,1,1,1,1,Criança (0,criança,3,4
...,...,...,...,...,...,...,...,...,...
20177,lag_benchmark/fff74322fa07c7c1.jpg,0,0,0,0,Adulto,adulto,40,41
20178,lag_benchmark/fff934bd1ff95af5.jpg,0,0,0,0,Idoso,idoso,80,76
20179,lag_benchmark/fffb40d02f510b35.jpg,1,0,1,0,Adolescente,adulto,15,18
20180,lag_benchmark/ffff1ad4bf685255.jpg,0,0,0,0,Adulto,adulto,25,22
20181,lag_benchmark/ffff369453fcbdde.jpg,0,0,0,0,Adulto,adulto,50,54

In [ ]:
resultadosIntern['previsao_prompt3'].value_counts()

previsao_prompt3
adulto         12725
criança         4738
idoso           1911
adolescente      808
Name: count, dtype: int64

**Tratamento de resultados do modelo**

In [ ]:
resultadosIntern['previsao_prompt3'] = resultadosIntern['previsao_prompt3'].apply(lambda x: 'Criança' if x not in ['Criança', 'Adulto', 'Adolescente','Idoso'] else x).str.lower()

In [ ]:
resultadosIntern['previsao_prompt4'] =  resultadosIntern['previsao_prompt4'].replace('Não posso determin', '0')

### Análise de Dados

In [ ]:
from sklearn.metrics import (balanced_accuracy_score,precision_score,recall_score, mean_absolute_error, accuracy_score )

In [ ]:
rotulo = resultadosIntern['real_prompt2']
previsao = resultadosIntern['previsao_prompt2']
round(balanced_accuracy_score(rotulo, previsao)*100, 1), round(precision_score(rotulo, previsao, pos_label='1')*100, 1), round(recall_score(rotulo, previsao, pos_label='1')*100, 1)

(np.float64(93.3), 75.0, 98.7)

**Multiclasses**

In [ ]:
rotulo = resultadosIntern['real_prompt3']
previsao = resultadosIntern['previsao_prompt3']
round(balanced_accuracy_score(rotulo, previsao)*100, 1), round(precision_score(rotulo, previsao, average='weighted')*100, 1), round(recall_score(rotulo, previsao, average='weighted')*100, 1)

(np.float64(71.6), 88.1, 86.7)

**Idade**

In [ ]:
for clas in ['criança', 'adolescente', 'adulto', 'idoso']:
    rotulo = resultadosIntern[resultadosIntern['real_prompt3'] == clas]['real_prompt4']
    previsao = resultadosIntern[resultadosIntern['real_prompt3'] == clas]['previsao_prompt4']

    print(f'MAE {clas}:', round(mean_absolute_error(rotulo, previsao), 1))

MAE criança: 1.2
MAE adolescente: 3.3
MAE adulto: 6.0
MAE idoso: 10.1

# No face

In [ ]:
resultadosIntern_nf = pd.DataFrame()

In [ ]:
# pasta onde estão os csvs
PASTA_CSV = "/content/drive/MyDrive/lagenda/resultados_InternVL/grupo1-noface"

# pega todos os arquivos csv
arquivos = sorted(
    glob.glob(os.path.join(PASTA_CSV, "*.csv")),
    key=lambda x: int(x.split("_p")[-1].split(".")[0])
)
print(arquivos)

# dataframe final
resultadosIntern_nf['img_name'] = idades_por_imagem['img_name']

# percorre cada csv
for i, arquivo in enumerate(arquivos, start=1):

    # lê csv
    df_result = pd.read_csv(arquivo)

    nome_prev = f"previsao_prompt{i}"
    nome_real = f"real_prompt{i}"

    resultadosIntern_nf[nome_prev] = df_result["resposta_modelo"]
    resultadosIntern_nf[nome_real] = real[i-1]

resultadosIntern_nf

['/content/drive/MyDrive/lagenda/resultados_InternVL/grupo1-noface/resultados_internvl3_p1.csv', '/content/drive/MyDrive/lagenda/resultados_InternVL/grupo1-noface/resultados_internvl3_p2.csv', '/content/drive/MyDrive/lagenda/resultados_InternVL/grupo1-noface/resultados_internvl3_p3.csv', '/content/drive/MyDrive/lagenda/resultados_InternVL/grupo1-noface/resultados_internvl3_p4.csv']

,img_name,previsao_prompt1,real_prompt1,previsao_prompt2,real_prompt2,previsao_prompt3,real_prompt3,previsao_prompt4,real_prompt4
0,lag_benchmark/0000339d0372e7e6.jpg,0.0,0,0.0,0,Adulto,adulto,25,27
1,lag_benchmark/0004350a376865f5.jpg,1.0,1,1.0,1,Criança (0,criança,3,5
2,lag_benchmark/00059fa95ee95e65.jpg,0.0,0,0.0,0,Adulto,idoso,25,79
3,lag_benchmark/0007473cdbe8c18d.jpg,1.0,1,1.0,1,Criança (0,criança,5,6
4,lag_benchmark/000851174d48d3d9.jpg,1.0,1,1.0,1,Criança (0,criança,4,4
...,...,...,...,...,...,...,...,...,...
20177,lag_benchmark/fff74322fa07c7c1.jpg,0.0,0,0.0,0,Adulto,adulto,35,41
20178,lag_benchmark/fff934bd1ff95af5.jpg,0.0,0,0.0,0,Idoso,idoso,70,76
20179,lag_benchmark/fffb40d02f510b35.jpg,0.0,0,0.0,0,Adulto,adulto,18,18
20180,lag_benchmark/ffff1ad4bf685255.jpg,0.0,0,0.0,0,Adulto,adulto,25,22
20181,lag_benchmark/ffff369453fcbdde.jpg,0.0,0,0.0,0,Adulto,adulto,50,54

In [ ]:
resultadosIntern_nf['previsao_prompt3'].value_counts()

previsao_prompt3
Adulto         13920
Criança (0      3860
Idoso           1404
Adolescente      627
Criança          371
Name: count, dtype: int64

In [ ]:
resultadosIntern_nf['previsao_prompt1'] = (resultadosIntern_nf['previsao_prompt1'].astype(float).astype(int).astype(str))
resultadosIntern_nf['previsao_prompt2'] = (resultadosIntern_nf['previsao_prompt2'].astype(float).astype(int).astype(str))
resultadosIntern_nf['real_prompt2'] = resultadosIntern['real_prompt2'].astype(str)

In [ ]:
resultadosIntern_nf['previsao_prompt3'] = resultadosIntern_nf['previsao_prompt3'].apply(lambda x: 'Criança' if x == 'Criança (0' else x).str.lower()

In [ ]:
resultadosIntern_nf['previsao_prompt4'] =  resultadosIntern_nf['previsao_prompt4'].replace('Não posso determin', '0')

In [ ]:
resultadosIntern_nf

,img_name,previsao_prompt1,real_prompt1,previsao_prompt2,real_prompt2,previsao_prompt3,real_prompt3
0,lag_benchmark/0000339d0372e7e6.jpg,0,0,0,0,adulto,adulto
1,lag_benchmark/0004350a376865f5.jpg,1,1,1,1,criança,criança
2,lag_benchmark/00059fa95ee95e65.jpg,0,0,0,0,adulto,idoso
3,lag_benchmark/0007473cdbe8c18d.jpg,1,1,1,1,criança,criança
4,lag_benchmark/000851174d48d3d9.jpg,1,1,1,1,criança,criança
...,...,...,...,...,...,...,...
20177,lag_benchmark/fff74322fa07c7c1.jpg,0,0,0,0,adulto,adulto
20178,lag_benchmark/fff934bd1ff95af5.jpg,0,0,0,0,idoso,idoso
20179,lag_benchmark/fffb40d02f510b35.jpg,0,0,0,0,adulto,adulto
20180,lag_benchmark/ffff1ad4bf685255.jpg,0,0,0,0,adulto,adulto
20181,lag_benchmark/ffff369453fcbdde.jpg,0,0,0,0,adulto,adulto

In [ ]:
rotulo = resultadosIntern_nf['real_prompt2']
previsao = resultadosIntern_nf['previsao_prompt2']
round(balanced_accuracy_score(rotulo, previsao)*100, 1), round(precision_score(rotulo, previsao, average='weighted')*100, 1), round(recall_score(rotulo, previsao, average='weighted')*100, 1)

(np.float64(91.8), 93.7, 93.7)

In [ ]:
rotulo = resultadosIntern_nf['real_prompt3']
previsao = resultadosIntern_nf['previsao_prompt3']
round(balanced_accuracy_score(rotulo, previsao)*100, 1), round(precision_score(rotulo, previsao, average='weighted')*100, 1), round(recall_score(rotulo, previsao, average='weighted')*100, 1)

(np.float64(60.6), 83.7, 81.8)

In [ ]:
for clas in ['criança', 'adolescente', 'adulto', 'idoso']:
    rotulo = resultadosIntern_nf[resultadosIntern_nf['real_prompt3'] == clas]['real_prompt4']
    previsao = resultadosIntern_nf[resultadosIntern_nf['real_prompt3'] == clas]['previsao_prompt4']

    print(f'MAE {clas}:', round(mean_absolute_error(rotulo, previsao), 1))

MAE criança: 2.5
MAE adolescente: 4.9
MAE adulto: 9.1
MAE idoso: 16.7

# Json

In [3]:
# idades_por_imagem

real = {'real_prompt1': [], 'real_prompt2': [],
        'real_prompt3': [], 'real_prompt4': []}

for idade in idades_por_imagem['age']:
    real['real_prompt1'].append([])
    real['real_prompt2'].append([])
    real['real_prompt3'].append([])
    real['real_prompt4'].append([])

    for i in idade:
        real['real_prompt1'][-1].append("1" if i <= 13 else "0")
        real['real_prompt2'][-1].append("1" if i <= 17 else "0")
        real['real_prompt4'][-1].append(i)

        if i <= 13:
            valor = "criança"
        elif i <= 17:
            valor = "adolescente"
        elif i <= 59:
            valor = "adulto"
        else:
            valor = "idoso"

        real['real_prompt3'][-1].append(valor)

In [8]:
pred_prompt1 = pd.read_csv('/content/drive/MyDrive/lagenda/resultados_InternVL/grupo2/resultados_internvl3_json_p1.csv')
pred_prompt2 = pd.read_csv('/content/drive/MyDrive/lagenda/resultados_InternVL/grupo2/resultados_internvl3_json_p2.csv')
pred_prompt3 = pd.read_csv('/content/drive/MyDrive/lagenda/resultados_InternVL/grupo2/resultados_internvl3_json_p3.csv')
pred_prompt4 = pd.read_csv('/content/drive/MyDrive/lagenda/resultados_InternVL/grupo2/resultados_internvl3_json_p4.csv')

In [11]:
resultadosInternJSON = pd.DataFrame()

resultadosInternJSON['img_name'] = idades_por_imagem['img_name']
resultadosInternJSON['real_prompt1'] = real['real_prompt1']
resultadosInternJSON['real_prompt2'] = real['real_prompt2']

for nome, pred in zip(['pred_prompt1', 'pred_prompt2'], [pred_prompt1, pred_prompt2]):
    respostas = []
    for indice in range(len(pred)):
        linha = pred.iloc[indice]
        respostas.append([])

        try:
            dict_resultado = eval(linha['resposta_modelo'])
            for pessoa in dict_resultado['pessoas']:
                respostas[-1].append("1" if pessoa['categoria'] == 'criança' else "0")
        except:
            txt = linha['resposta_modelo']
            respostas[-1] = ["1"] * txt.count('criança')
            respostas[-1].extend(["0"] * txt.count('adulto'))

    resultadosInternJSON[nome] = respostas

##################
str2class = lambda lst: [['criança', 'adolescente', 'adulto', 'idoso'].index(item) for item in lst]
resultadosInternJSON['real_prompt3'] = list(map(str2class, real['real_prompt3']))

respostas = []
for indice in range(len(pred_prompt3)):
    linha = pred_prompt3.iloc[indice]
    respostas.append([])

    try:
        dict_resultado = eval(linha['resposta_modelo'])
        for pessoa in dict_resultado['pessoas']:
            if pessoa['categoria'] == 'adulta':
                pessoa['categoria'] = 'adulto'
            respostas[-1].append(['criança', 'adolescente', 'adulto', 'idoso'].index(pessoa['categoria'].lower()))
    except:
        txt = linha['resposta_modelo'].lower()
        txt = ' '.join(txt.split('}')[:-1])
        respostas[-1].extend([0] * txt.count('criança'))
        respostas[-1].extend([1] * txt.count('adolescente'))
        respostas[-1].extend([2] * txt.count('adulto'))
        respostas[-1].extend([3] * txt.count('idoso'))

resultadosInternJSON['pred_prompt3'] = respostas


resultadosInternJSON['real_prompt4'] = real['real_prompt4']
respostas = []
for indice in range(len(pred_prompt4)):
    linha = pred_prompt4.iloc[indice]
    respostas.append([])

    try:
        dict_resultado = eval(linha['resposta_modelo'])
        for pessoa in dict_resultado['pessoas']:
            respostas[-1].append(pessoa['idade'])
    except:
        txt = linha['resposta_modelo']
        pos = txt.find('idade')
        while pos != -1:
            respostas[-1].append(txt[pos:].split(':')[1].split('}')[0].strip())
            pos = txt.find('idade', pos+1)

resultadosInternJSON['pred_prompt4'] = respostas
resultadosInternJSON['pred_prompt4'] = resultadosInternJSON['pred_prompt4'].apply(lambda lst: [min(int(x or 0), 100) for x in lst])

In [12]:
resultadosInternJSON

,img_name,real_prompt1,real_prompt2,pred_prompt1,pred_prompt2,real_prompt3,pred_prompt3,real_prompt4,pred_prompt4
0,lag_benchmark/0000339d0372e7e6.jpg,[0],[0],[0],[0],[2],[2],[27],[30]
1,lag_benchmark/0004350a376865f5.jpg,"[1, 1]","[1, 1]","[1, 1]","[1, 1]","[0, 0]","[0, 0]","[5, 6]","[5, 4]"
2,lag_benchmark/00059fa95ee95e65.jpg,[0],[0],[0],[0],[3],[3],[79],[60]
3,lag_benchmark/0007473cdbe8c18d.jpg,[1],[1],[1],[1],[0],[0],[6],[5]
4,lag_benchmark/000851174d48d3d9.jpg,[1],[1],"[1, 0]","[1, 0]",[0],"[0, 2]",[4],[3]
...,...,...,...,...,...,...,...,...,...
20177,lag_benchmark/fff74322fa07c7c1.jpg,[0],[0],[0],[0],[2],[2],[41],[40]
20178,lag_benchmark/fff934bd1ff95af5.jpg,[0],[0],[0],[0],[3],[3],[76],[75]
20179,lag_benchmark/fffb40d02f510b35.jpg,[0],[0],[0],[0],[2],[1],[18],[18]
20180,lag_benchmark/ffff1ad4bf685255.jpg,[0],[0],[0],[0],[2],[2],[22],[25]
20181,lag_benchmark/ffff369453fcbdde.jpg,[0],[0],[0],[0],[2],[2],[54],[55]

In [15]:
from sklearn.metrics import (
    balanced_accuracy_score,
    accuracy_score, precision_score,
    recall_score, mean_absolute_error,
    confusion_matrix
)

In [16]:
from sklearn.preprocessing import MultiLabelBinarizer

#1, 2, 3
for i in range(1, 4):
    mlb = MultiLabelBinarizer()
    y_true_bin = mlb.fit_transform(resultadosInternJSON[f'real_prompt{i}'])
    y_pred_bin = mlb.transform(resultadosInternJSON[f'pred_prompt{i}'])

    acc = accuracy_score(y_true_bin, y_pred_bin,)
    prec = precision_score(y_true_bin, y_pred_bin, average='weighted')
    rec = recall_score(y_true_bin, y_pred_bin, average='weighted')
    print(acc, prec, rec)

0.952086017243088 0.9581370931642927 0.9746133071446108
0.947626597958577 0.9524201841535314 0.9694813797164026
0.8487265880487563 0.8780739132492243 0.8816615911686334

In [18]:
from scipy.stats import wasserstein_distance
import numpy as np

for clas in range(4):
    val = []
    rotulo = resultadosInternJSON[resultadosInternJSON['real_prompt3'].apply(lambda x: clas in x and len(x) > 1)]['real_prompt4']
    previsao = resultadosInternJSON[resultadosInternJSON['real_prompt3'].apply(lambda x: clas in x and len(x) > 1)]['pred_prompt4']

    for gt, y in zip(rotulo, previsao):
        w = wasserstein_distance(gt, y)
        val.append(w)
    print(round(np.mean(val), 1))

2.2
3.4
5.8
6.6